### ISSUE TITLE
Issue on Android 29

### ISSUE THREAD

**Issue by mr-thierry** [beworker/edge-to-edge#2]
It appears that the implementation doesn't work properly when I set _edge-to-edge_ on an _Activity_. The bottom navigation bar is still fully transparent. For example:

![device-2020-06-15-073908](https://user-images.githubusercontent.com/784268/84653513-8f17e480-aedb-11ea-8a59-e729b30d3eda.png)

What I want is to have the bottom navigation bar semi-transparent:
![device-2020-06-15-074115](https://user-images.githubusercontent.com/784268/84653584-b078d080-aedb-11ea-95cf-63397f007624.png)

My fix is to have the Edge-to-Edge use the "android.R.id.content" view as the root view instead of the decor view.

I have created a project that shows the issue and the fix. See https://github.com/thierryd/EdgeToEdgeActivityIssue

**Comment by sergejsha** [comment]
Fixed in `1.0-rc1`, which is on the way.

**Comment by mr-thierry** [comment]
@beworker Good job on fixing it and doing a fast release! I confirm that it work well for me. And also good job on adding a FullscreenActivity to the sample.  I didn't want to point that it was needed (didn't want to look like an old grumpy user ;) ), but it is certainly a good idea! :)

**Comment by sergejsha** [comment]
Thanks man for your effort of creating a demo project, showing the bug, and the solution. It was extremely helpful and speeded up the fix. Having the screen in the demo app appeared to be a good long-term time "investment", that's why I decided to add it :)
